### ISSUE TITLE
告示牌导致游戏闪退

### ISSUE THREAD

**Issue by SnifferGX** [ZiYueCommentary/Tianjin-Metro#2]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/ZiYueCommentary/Tianjin-Metro/issues) before.
- [X] This bug still exists in the latest version of the Tianjin Metro mod.
- [X] I have tested this in the official version of Tianjin Metro, not a modified, custom, or unofficial build.

### Describe the Bug

d打开游戏因告示牌而闪退（PCL报错）

### Reproduction Steps

1.
2.
3.

### In-game Log and Crash Report

https://wwrv.lanzn.com/izfGq29s5i7a
https://wwrv.lanzn.com/iRkfv29s5jwb

### Mod Loader

Fabric

### Minecraft Version

1.20.1

### Minecraft Transit Railway Version

4.00 Beta 9

### Tianjin Metro Version

1.00 Beta 1

### Operating System

Windows 10 64位

### List of Mods or Modpack You Were Using

https://wwrv.lanzn.com/iE1Ui29s5urc

**Comment by ZiYueCommentary** [comment]
天津地铁模组支持MTR 4.0.0 beta-8，暂不支持beta-9。对于beta-9的支持将在天津地铁1.0.0-beta-2可用（2024年10月1日）

**Comment by superboy114514** [comment]
没错，我因为这个崩了个档
