### ISSUE TITLE
创世神无法复制本模组墙上的告示牌

### ISSUE THREAD

**Issue by duduskz** [ZiYueCommentary/Tianjin-Metro#5]
### Before reporting, I have confirmed that

- [X] This bug does not appear to be reported on [GitHub Issues](https://github.com/ZiYueCommentary/Tianjin-Metro/issues) before.
- [X] This bug still exists in the latest version of the Tianjin Metro mod.
- [X] I have tested this in the official version of Tianjin Metro, not a modified, custom, or unofficial build.

### Describe the Bug

我习惯使用创世神的复制粘贴来复制地铁站，但是我的地铁站大量使用到了本模组墙上的告示牌，这使我每次都需要重新放告示牌并且编辑内容，但是创世神却可以复制本模组天花板上的告示牌

### Reproduction Steps

1. 使用创世神//copy
2. //paste后墙上的所有告示牌变为拆除粒子并拆除

### In-game Log and Crash Report

无

### Mod Loader

Fabric

### Minecraft Version

1.20.4

### Minecraft Transit Railway Version

4.0.0

### Tianjin Metro Version

1.0.0-beta1

### Operating System

Windows 11

### List of Mods or Modpack You Were Using

![image](https://github.com/user-attachments/assets/5c1e5bc2-4c84-4996-bfd5-c4ce59c0d594)

**Comment by ZiYueCommentary** [comment]
您好，哪种告示牌？

**Comment by duduskz** [comment]
我写错了，是指示牌

**Comment by ZiYueCommentary** [comment]
哪种指示牌？

**Comment by duduskz** [comment]
![image](https://github.com/user-attachments/assets/800ca197-01f3-4cf8-82b8-3d1ca5c1cbbe)

**Comment by ZiYueCommentary** [comment]
经测试并没有问题，请检查指示牌复制后是否不悬空。

**Comment by duduskz** [comment]
https://github.com/user-attachments/assets/432c95d0-9b10-4fd4-8c19-aad635b443a9

**Comment by ZiYueCommentary** [comment]
感谢您的反馈！请等待Github Action构建完毕，并下载最新版本：https://github.com/ZiYueCommentary/Tianjin-Metro/actions/runs/10969052358
